from __future__ import annotations

from typing import Any, Dict, List, Optional, Protocol


class DatabaseRepository(Protocol):
    def create_user(self, username: str, password_hash: str, password_salt: str) -> Dict[str, Any]:
        ...

    def get_user_credentials(self, username: str) -> Optional[Dict[str, str]]:
        ...

    def get_user(self, username: str) -> Optional[Dict[str, Any]]:
        ...

    def get_user_by_username(self, username: str) -> Optional[Dict[str, Any]]:
        ...

    def create_session(self, username: str, session_id: str, session_hash: str, expires_at: str) -> Dict[str, Any]:
        ...

    def get_session(self, session_id: str) -> Optional[Dict[str, Any]]:
        ...

    def delete_session(self, session_id: str) -> bool:
        ...

    def get_tags(self, username: str) -> List[str]:
        ...

    def add_tag(self, username: str, tag: str) -> bool:
        ...

    def delete_tag(self, username: str, tag: str) -> bool:
        ...

    def get_notes(self, username: str) -> List[Dict[str, Any]]:
        ...

    def list_folders(self, username: str) -> List[Dict[str, Any]]:
        ...

    def get_folder(self, username: str, folder_id: str) -> Optional[Dict[str, Any]]:
        ...

    def create_folder(self, username: str, name: str) -> Dict[str, Any]:
        ...

    def list_exam_folders(self, username: str) -> List[Dict[str, Any]]:
        ...

    def get_exam_folder(self, username: str, folder_id: str) -> Optional[Dict[str, Any]]:
        ...

    def create_exam_folder(self, username: str, name: str) -> Dict[str, Any]:
        ...

    def get_exam_folder_analysis(self, username: str, folder_id: str) -> Optional[Dict[str, Any]]:
        ...

    def save_exam_folder_analysis(self, username: str, folder_id: str, analysis: Dict[str, Any]) -> Dict[str, Any]:
        ...

    def update_exam_folder_analysis(self, username: str, folder_id: str, **updates: Any) -> Dict[str, Any]:
        ...

    def add_note(self, username: str, content: str) -> Optional[Dict[str, Any]]:
        ...

    def delete_note(self, username: str, note_id: str) -> bool:
        ...

    def set_document_metadata(self, username: str, filename: str, metadata: Dict[str, Any]) -> None:
        ...

    def get_document_metadata(self, username: str, filename: str) -> Optional[Dict[str, Any]]:
        ...

    def set_document_folder(self, username: str, filename: str, folder_id: Optional[str]) -> Dict[str, Any]:
        ...

    def list_exam_documents(self, username: str) -> List[Dict[str, Any]]:
        ...

    def add_exam_document(self, username: str, document: Dict[str, Any]) -> Dict[str, Any]:
        ...

    def get_exam_document(self, username: str, document_id: str) -> Optional[Dict[str, Any]]:
        ...

    def update_exam_document_folder(self, username: str, document_id: str, folder_id: str) -> Dict[str, Any]:
        ...

    def delete_document_metadata(self, username: str, filename: str) -> bool:
        ...

    def get_all_metadata(self, username: str) -> Dict[str, Any]:
        ...
